### PR TITLE
Updated sendbox url in payment processor & Proxy Class

### PR DESCRIPTION
**Pull request by jigarsangoi**
1) Updated sandbox url in payment processor & Proxy Class  #1
2) Removed encoding from Buyer's name #2
3) login url for Gestpay login 
4) Added our name in Description file

### CODE REVIEW

**Comment by landlogicit** [comment]
Your code is in testing.... Please wait...

**Review by landlogicit — CHANGES_REQUESTED** [review]
Hi. Thank you for your contribution. We can only accept code improvements and bug fixes. In its case there is simply a change in string value. Nothing more. The proxy class is generated automatically. So the Description file remains unchanged we do not accept the change.

**Comment by jigarsangoi** [comment]
I done suggested changes

**Comment by landlogicit** [comment]
Hi, thanks for your changes.

**Pull request merged**
